import { JobApplication, ApplicationEvent } from '@/types/application';
import { UserProfile } from '@/types/user';

export const INITIAL_MOCK_PROFILE: UserProfile = {
  id: 'usr_demo_789',
  email: 'alex.developer@example.com',
  full_name: 'Alex Morgan',
  headline: 'Senior Full Stack Engineer',
  target_role: 'Full Stack Engineer / Tech Lead',
  location: 'San Francisco, CA (Remote)',
  created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  updated_at: new Date().toISOString(),
};

export const INITIAL_MOCK_APPLICATIONS: JobApplication[] = [
  {
    id: 'app-1',
    user_id: 'usr_demo_789',
    company_name: 'Stripe',
    job_title: 'Staff Frontend Engineer',
    job_type: 'Full-time',
    location: 'Remote, US',
    salary: '$190,000 - $225,000',
    job_url: 'https://stripe.com/jobs/staff-frontend',
    application_date: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    deadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: 'Interview',
    notes: 'Technical screen scheduled with Engineering Manager. Review React internals and system design architecture for billing dashboard.',
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'app-2',
    user_id: 'usr_demo_789',
    company_name: 'Linear',
    job_title: 'Full Stack Engineer',
    job_type: 'Remote',
    location: 'San Francisco / Remote',
    salary: '$175,000 - $210,000 + Equity',
    job_url: 'https://linear.app/careers/full-stack',
    application_date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    deadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: 'Screening',
    notes: 'Recruiter reached out on LinkedIn. Had a 25min introductory call regarding their sync engine and local-first architecture.',
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'app-3',
    user_id: 'usr_demo_789',
    company_name: 'Vercel',
    job_title: 'Senior Solutions Architect',
    job_type: 'Full-time',
    location: 'Remote',
    salary: '$180,000 - $215,000',
    job_url: 'https://vercel.com/careers',
    application_date: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    deadline: null,
    status: 'Offer',
    notes: 'Official offer received! Base: $185k, 40k RSUs over 4 years. Decision required by next Friday.',
    created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'app-4',
    user_id: 'usr_demo_789',
    company_name: 'Figma',
    job_title: 'Product Engineer - Design Systems',
    job_type: 'Full-time',
    location: 'San Francisco, CA (Hybrid)',
    salary: '$185,000 - $220,000',
    job_url: 'https://figma.com/careers',
    application_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    deadline: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: 'Applied',
    notes: 'Submitted via employee referral from former colleague. Included portfolio and design system open source links.',
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'app-5',
    user_id: 'usr_demo_789',
    company_name: 'Supabase',
    job_title: 'Developer Advocate / Engineer',
    job_type: 'Remote',
    location: 'Remote worldwide',
    salary: '$160,000 - $190,000',
    job_url: 'https://supabase.com/careers',
    application_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    deadline: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: 'Applied',
    notes: 'Submitted application emphasizing Postgres, realtime subscriptions, and developer documentation experience.',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'app-6',
    user_id: 'usr_demo_789',
    company_name: 'Datadog',
    job_title: 'Senior Software Engineer',
    job_type: 'Full-time',
    location: 'New York, NY',
    salary: '$170,000 - $200,000',
    job_url: 'https://datadoghq.com/careers',
    application_date: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    deadline: null,
    status: 'Rejected',
    notes: 'Received automated rejection after initial application review. They required 8+ years Go backend specific experience.',
    created_at: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'app-7',
    user_id: 'usr_demo_789',
    company_name: 'Airbnb',
    job_title: 'Frontend Platform Engineer',
    job_type: 'Full-time',
    location: 'San Francisco, CA',
    salary: '$180,000 - $210,000',
    job_url: 'https://airbnb.com/careers',
    application_date: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    deadline: null,
    status: 'Withdrawn',
    notes: 'Withdrew candidature after receiving Vercel offer due to location requirement.',
    created_at: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_MOCK_EVENTS: ApplicationEvent[] = [
  {
    id: 'evt-1',
    application_id: 'app-1',
    user_id: 'usr_demo_789',
    event_type: 'APPLICATION_CREATED',
    title: 'Application Submitted',
    description: 'Applied for Staff Frontend Engineer at Stripe',
    event_date: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'evt-2',
    application_id: 'app-1',
    user_id: 'usr_demo_789',
    event_type: 'STATUS_CHANGE',
    title: 'Status changed to Screening',
    description: 'Stage updated from Applied to Screening',
    event_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'evt-3',
    application_id: 'app-1',
    user_id: 'usr_demo_789',
    event_type: 'STATUS_CHANGE',
    title: 'Status changed to Interview',
    description: 'Stage updated from Screening to Interview',
    event_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'evt-4',
    application_id: 'app-1',
    user_id: 'usr_demo_789',
    event_type: 'INTERVIEW',
    title: 'Technical Screen Scheduled',
    description: 'Meeting with Engineering Lead on Zoom. Topics: architecture & performance.',
    event_date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'evt-5',
    application_id: 'app-3',
    user_id: 'usr_demo_789',
    event_type: 'OFFER',
    title: 'Formal Offer Received',
    description: 'Written offer received via DocuSign with competitive compensation package.',
    event_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
